### ISSUE TITLE
'public using _'  errors

### ISSUE THREAD

**Issue by wilsonk** [blat-blatnik/BeefWin32#2]
Not sure why (perhaps Beef version 0.43.3 is too new?), but I get a bunch of errors along the lines of this when trying to build the example:
```
ERROR: Invalid token at line 9847:11 in d:\handmade-beef\src\Win32\Foundation.bf
   public using _Anonymous_e__Struct Anonymous;
          ^^^^^
```

If anyone else ends up with this problem you can just run this on an MSYS2/Git-bash/MinGW command line to fix things (it just gets rid of the 'using' keyword on each line in all the files of the directory):
```
find ./ -type f -exec sed -i 's/public using _/public _/' {} \;
```

The example works for me after this change.

**Comment by blat-blatnik** [comment]
I think you got this error because you were using an older version of Beef. I'm not sure when `public using SomeSubclass` was added but it was a while ago. Anyway these bindings always require the latest nightly version, I added that to the readme now.
